# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Calculator-UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 741, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 110, 741, 603))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_M = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_M.setFont(font)
        self.pushButton_M.setObjectName("pushButton_M")
        self.gridLayout_2.addWidget(self.pushButton_M, 0, 2, 1, 1)
        self.pushButton_MR = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_MR.setFont(font)
        self.pushButton_MR.setObjectName("pushButton_MR")
        self.gridLayout_2.addWidget(self.pushButton_MR, 0, 3, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout_2.addWidget(self.pushButton_add, 4, 4, 1, 1)
        self.pushButton_RE = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_RE.setFont(font)
        self.pushButton_RE.setObjectName("pushButton_RE")
        self.gridLayout_2.addWidget(self.pushButton_RE, 0, 0, 1, 1)
        self.pushButton_mul = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.gridLayout_2.addWidget(self.pushButton_mul, 1, 4, 1, 1)
        self.pushButton_n9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_n9.setFont(font)
        self.pushButton_n9.setObjectName("pushButton_n9")
        self.gridLayout_2.addWidget(self.pushButton_n9, 1, 3, 1, 1)
        self.pushButton_n3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_n3.setFont(font)
        self.pushButton_n3.setObjectName("pushButton_n3")
        self.gridLayout_2.addWidget(self.pushButton_n3, 4, 3, 1, 1)
        self.pushButton_n1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_n1.setFont(font)
        self.pushButton_n1.setObjectName("pushButton_n1")
        self.gridLayout_2.addWidget(self.pushButton_n1, 4, 0, 1, 1)
        self.pushButton_div = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setObjectName("pushButton_div")
        self.gridLayout_2.addWidget(self.pushButton_div, 0, 4, 1, 1)
        self.pushButton_n0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_n0.setFont(font)
        self.pushButton_n0.setObjectName("pushButton_n0")
        self.gridLayout_2.addWidget(self.pushButton_n0, 5, 0, 1, 1)
        self.pushButton_n5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_n5.setFont(font)
        self.pushButton_n5.setObjectName("pushButton_n5")
        self.gridLayout_2.addWidget(self.pushButton_n5, 2, 2, 1, 1)
        self.pushButton_n4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_n4.setFont(font)
        self.pushButton_n4.setObjectName("pushButton_n4")
        self.gridLayout_2.addWidget(self.pushButton_n4, 2, 0, 1, 1)
        self.pushButton_n8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_n8.setFont(font)
        self.pushButton_n8.setObjectName("pushButton_n8")
        self.gridLayout_2.addWidget(self.pushButton_n8, 1, 2, 1, 1)
        self.pushButton_n2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_n2.setFont(font)
        self.pushButton_n2.setObjectName("pushButton_n2")
        self.gridLayout_2.addWidget(self.pushButton_n2, 4, 2, 1, 1)
        self.pushButton_n7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_n7.setFont(font)
        self.pushButton_n7.setObjectName("pushButton_n7")
        self.gridLayout_2.addWidget(self.pushButton_n7, 1, 0, 1, 1)
        self.pushButton_n6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_n6.setFont(font)
        self.pushButton_n6.setObjectName("pushButton_n6")
        self.gridLayout_2.addWidget(self.pushButton_n6, 2, 3, 1, 1)
        self.pushButton_div100 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_div100.setFont(font)
        self.pushButton_div100.setObjectName("pushButton_div100")
        self.gridLayout_2.addWidget(self.pushButton_div100, 5, 2, 1, 1)
        self.pushButton_sub = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_sub.setFont(font)
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.gridLayout_2.addWidget(self.pushButton_sub, 2, 4, 1, 1)
        self.pushButton_equ = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        self.pushButton_equ.setFont(font)
        self.pushButton_equ.setObjectName("pushButton_equ")
        self.gridLayout_2.addWidget(self.pushButton_equ, 5, 3, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_M.setText(_translate("MainWindow", "M"))
        self.pushButton_MR.setText(_translate("MainWindow", "MR"))
        self.pushButton_add.setText(_translate("MainWindow", "+"))
        self.pushButton_RE.setText(_translate("MainWindow", "RE"))
        self.pushButton_mul.setText(_translate("MainWindow", "X"))
        self.pushButton_n9.setText(_translate("MainWindow", "9"))
        self.pushButton_n3.setText(_translate("MainWindow", "3"))
        self.pushButton_n1.setText(_translate("MainWindow", "1"))
        self.pushButton_div.setText(_translate("MainWindow", "/"))
        self.pushButton_n0.setText(_translate("MainWindow", "0"))
        self.pushButton_n5.setText(_translate("MainWindow", "5"))
        self.pushButton_n4.setText(_translate("MainWindow", "4"))
        self.pushButton_n8.setText(_translate("MainWindow", "8"))
        self.pushButton_n2.setText(_translate("MainWindow", "2"))
        self.pushButton_n7.setText(_translate("MainWindow", "7"))
        self.pushButton_n6.setText(_translate("MainWindow", "6"))
        self.pushButton_div100.setText(_translate("MainWindow", "/100"))
        self.pushButton_sub.setText(_translate("MainWindow", "-"))
        self.pushButton_equ.setText(_translate("MainWindow", "="))
